version: '3.9'

services:
  quiz_telegram_bot:
    image: quiz_bot_image
    volumes:
      - ./:/app
    build: .
    container_name: quiz_bot_container
    env_file:
      - .env
    restart: unless-stopped
